"""Recovery event types (Sprint 1.0.4).

Event OBJECTS are the existing :class:`agent.runtime.events.RuntimeEvent` —
this layer only adds the recovery-specific type constants, so the whole
audit trail stays ONE uniform stream in ``agent_v2_events``.
"""

RECOVERY_SCANNED = "RECOVERY_SCANNED"
RECOVERY_CLASSIFIED = "RECOVERY_CLASSIFIED"
RECOVERY_RESUMED = "RECOVERY_RESUMED"
RECOVERY_WAITING = "RECOVERY_WAITING"
RECOVERY_MANUAL_REVIEW = "RECOVERY_MANUAL_REVIEW"
RECOVERY_VERIFYING = "RECOVERY_VERIFYING"
RECOVERY_VERIFIED = "RECOVERY_VERIFIED"
RECOVERY_VERIFICATION_FAILED = "RECOVERY_VERIFICATION_FAILED"
RECOVERY_REVIEWED = "RECOVERY_REVIEWED"
RECOVERY_SKIPPED = "RECOVERY_SKIPPED"

RECOVERY_EVENT_TYPES = frozenset(
    {
        RECOVERY_SCANNED,
        RECOVERY_CLASSIFIED,
        RECOVERY_RESUMED,
        RECOVERY_WAITING,
        RECOVERY_MANUAL_REVIEW,
        RECOVERY_VERIFYING,
        RECOVERY_VERIFIED,
        RECOVERY_VERIFICATION_FAILED,
        RECOVERY_REVIEWED,
        RECOVERY_SKIPPED,
    }
)
