"""Sprint 1.3.15 — event journal type constants.

These mirror the append-only journal section of the durable store.
"""
from __future__ import annotations

GLOBAL_CLAIMED = "GLOBAL_CLAIMED"
LOCK_ACQUIRED = "LOCK_ACQUIRED"
CHILD_PREPARED = "CHILD_PREPARED"
BARRIER_READY = "BARRIER_READY"
SIMULATION_STARTED = "SIMULATION_STARTED"
CHILD_SIMULATED = "CHILD_SIMULATED"
VERIFY_COMPLETED = "VERIFY_COMPLETED"
COMPENSATION_REQUIRED = "COMPENSATION_REQUIRED"
GLOBAL_SIMULATED_COMMIT = "GLOBAL_SIMULATED_COMMIT"
GLOBAL_FAILED = "GLOBAL_FAILED"

ALL_EVENTS = {
    GLOBAL_CLAIMED,
    LOCK_ACQUIRED,
    CHILD_PREPARED,
    BARRIER_READY,
    SIMULATION_STARTED,
    CHILD_SIMULATED,
    VERIFY_COMPLETED,
    COMPENSATION_REQUIRED,
    GLOBAL_SIMULATED_COMMIT,
    GLOBAL_FAILED,
}

__all__ = [
    "ALL_EVENTS",
    "BARRIER_READY",
    "CHILD_PREPARED",
    "CHILD_SIMULATED",
    "COMPENSATION_REQUIRED",
    "GLOBAL_CLAIMED",
    "GLOBAL_FAILED",
    "GLOBAL_SIMULATED_COMMIT",
    "LOCK_ACQUIRED",
    "SIMULATION_STARTED",
    "VERIFY_COMPLETED",
]