"""Canary policy constants; never equivalent to generic control."""
CAPABILITY="HERMES_MULTI_SERVICE_EXECUTION_CANARY"
OPERATION="SIMULATE_TWO_REGISTERED_AUX_SERVICES"
RISK="MEDIUM_MUTATION_MODEL"
BLAST="MULTI_SERVICE"
DENIED_EQUIVALENTS=frozenset({"SYSTEM_CONTROL","SERVICE_CONTROL","SERVICE_RESTART","SERVICE_RELOAD","FILE_WRITE","NETWORK","DATABASE_MUTATION"})
def capability_is_narrow(capability,operation):return capability==CAPABILITY and operation==OPERATION
